name: Usage
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
permissions: write-all

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - id: changed-files
        uses: tj-actions/changed-files@v39
        with:
          files: "**/*.{yml,yaml}"
      - uses: ./
        with:
          files: ${{ steps.changed-files.outputs.all_changed_files }}